from colorama import Fore
print(Fore.BLACK + "Hi negro")
print(Fore.RED + "Hi rojo")
print(Fore.GREEN + "Hi verde")
print(Fore.YELLOW + "Hi amarillo")
print(Fore.BLUE + "Hi azul")
print(Fore.MAGENTA + "Hi MAGENTA")
print(Fore.CYAN + "Hi CYAN")
print(Fore.WHITE + "Hi blanco")